networks:
  zipsoon-network:
    driver: bridge

services:
  db:
    image: postgis/postgis:15-3.4
    volumes:
      - ./common/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./batch/src/main/resources/schema/schema-postgresql.sql:/docker-entrypoint-initdb.d/02-schema-postgresql.sql
    ports:
      - "5432:5432"
    networks:
      - zipsoon-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  batch:
    networks:
      - zipsoon-network
    depends_on:
      db:
        condition: service_healthy

  api:
    ports:
      - "8080:8080"
    networks:
      - zipsoon-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/workspaces/zipsoon
