spring:
  profiles:
    default: local
  datasource:
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations:
    - classpath*:mapper/**/*.xml
    - classpath*:com/zipsoon/**/mapper/*.xml
  type-handlers-package: com.zipsoon.common.config.typehandler
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zipsoon.common.domain,com.zipsoon.api.interfaces.api.estate.dto
  mapper-scan-packages: com.zipsoon.api.interfaces.mapper,com.zipsoon.api.infrastructure.mapper,com.zipsoon.common.mapper

logging:
  level:
    root: INFO
    com.zipsoon.api: DEBUG
    com.zipsoon.api.interfaces.api: INFO
    com.zipsoon.api.application: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{X-Request-Id}] %-5level %logger{36} - %msg%n"

jwt:
  access-token-validity-in-milliseconds: 3600000
  refresh-token-validity-in-milliseconds: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
