on:
  push:
    branches: [ main ]
    paths:
      - 'api/src/**'
      - 'common/src/**'
  workflow_dispatch:

jobs:
  # 1. API 애플리케이션 빌드
  build-api-application:
    name: API 애플리케이션 빌드
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
      
      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Gradle로 API 모듈 빌드 실행
        run: ./gradlew :api:clean :api:build :common:build -x test
      
      - name: 빌드 결과물 업로드
        uses: actions/upload-artifact@v4
        with:
          name: api-build-artifacts
          path: |
            api/build/libs/*.jar
  
  # 2. 도커 이미지 빌드 및 배포 - API
  build-api-image:
    name: API 서비스 이미지 빌드
    needs: build-api-application
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
      
      - name: 빌드 결과물 다운로드
        uses: actions/download-artifact@v4
        with:
          name: api-build-artifacts
          path: api/build/libs
      
      - name: QEMU 설정 (멀티 아키텍처 지원)
        uses: docker/setup-qemu-action@v3
      
      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v3
      
      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: API 이미지 빌드 및 배포
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            electronyoon/zipsoon-api:latest
            electronyoon/zipsoon-api:${{ github.sha }}
  
  # 3. 배포 완료 알림
  notify-api-completion:
    name: API 배포 완료 알림
    needs: [build-api-image]
    runs-on: ubuntu-latest
    
    steps:
      - name: 배포 상태 요약
        run: |
          echo "API 이미지가 성공적으로 빌드되고 배포되었습니다."
          echo "API 이미지: electronyoon/zipsoon-api:latest"
          echo "커밋 해시: ${{ github.sha }}"
          echo "배포 시간: $(date)"