on:
  push:
    branches: [ main ]
    paths:
      - 'batch/src/**'
      - 'common/src/**'
  workflow_dispatch:

jobs:
  # 1. Batch 애플리케이션 빌드
  build-batch-application:
    name: Batch 애플리케이션 빌드
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
      
      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Gradle로 Batch 모듈 빌드 실행
        run: ./gradlew :batch:clean :batch:build :common:build -x test
      
      - name: 빌드 결과물 업로드
        uses: actions/upload-artifact@v4
        with:
          name: batch-build-artifacts
          path: |
            batch/build/libs/*.jar
            batch/src/main/resources/source
  
  # 2. 도커 이미지 빌드 및 배포 - Batch
  build-batch-image:
    name: Batch 서비스 이미지 빌드
    needs: build-batch-application
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
      
      - name: 빌드 결과물 다운로드
        uses: actions/download-artifact@v4
        with:
          name: batch-build-artifacts
      
      - name: QEMU 설정 (멀티 아키텍처 지원)
        uses: docker/setup-qemu-action@v3
      
      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v3
      
      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Batch 이미지 빌드 및 배포
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./batch/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            electronyoon/zipsoon-batch:latest
            electronyoon/zipsoon-batch:${{ github.sha }}
  
  # 3. 배포 완료 알림
  notify-batch-completion:
    name: Batch 배포 완료 알림
    needs: [build-batch-image]
    runs-on: ubuntu-latest
    
    steps:
      - name: 배포 상태 요약
        run: |
          echo "Batch 이미지가 성공적으로 빌드되고 배포되었습니다."
          echo "Batch 이미지: electronyoon/zipsoon-batch:latest"
          echo "커밋 해시: ${{ github.sha }}"
          echo "배포 시간: $(date)"