on:
  push:
    branches: [ main ]
    paths:
      - 'common/src/**'
      # API나 Batch에서 변경된 경우는 각각의 워크플로우에서 처리
      - '!api/src/**'
      - '!batch/src/**'
  workflow_dispatch:

jobs:
  # 1. Common 라이브러리 변경 시 모두 빌드
  build-all-applications:
    name: 모든 애플리케이션 빌드
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
      
      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Gradle로 빌드 실행
        run: ./gradlew clean build -x test
      
      - name: 빌드 결과물 업로드
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            api/build/libs/*.jar
            batch/build/libs/*.jar
            batch/src/main/resources/source
  
  # 2. 도커 이미지 빌드 및 배포 - API
  build-api-image:
    name: API 서비스 이미지 빌드
    needs: build-all-applications
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
      
      - name: 빌드 결과물 다운로드
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: api/build/libs
      
      - name: QEMU 설정 (멀티 아키텍처 지원)
        uses: docker/setup-qemu-action@v3
      
      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v3
      
      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: API 이미지 빌드 및 배포
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            electronyoon/zipsoon-api:latest
            electronyoon/zipsoon-api:${{ github.sha }}
  
  # 3. 도커 이미지 빌드 및 배포 - Batch
  build-batch-image:
    name: Batch 서비스 이미지 빌드
    needs: build-all-applications
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
      
      - name: 빌드 결과물 다운로드
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: batch/build/libs
          
      - name: 소스 디렉토리 복사
        run: |
          mkdir -p batch/src/main/resources
          cp -r $GITHUB_WORKSPACE/batch/src/main/resources/source batch/src/main/resources/
      
      - name: QEMU 설정 (멀티 아키텍처 지원)
        uses: docker/setup-qemu-action@v3
      
      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v3
      
      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Batch 이미지 빌드 및 배포
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./batch/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            electronyoon/zipsoon-batch:latest
            electronyoon/zipsoon-batch:${{ github.sha }}
  
  # 4. 배포 완료 알림
  notify-completion:
    name: 배포 완료 알림
    needs: [build-api-image, build-batch-image]
    runs-on: ubuntu-latest
    
    steps:
      - name: 배포 상태 요약
        run: |
          echo "공통 라이브러리 변경으로 모든 이미지가 성공적으로 재빌드되었습니다."
          echo "API 이미지: electronyoon/zipsoon-api:latest"
          echo "Batch 이미지: electronyoon/zipsoon-batch:latest"
          echo "커밋 해시: ${{ github.sha }}"
          echo "배포 시간: $(date)"
